import Head from "next/head";
import styles from "@/styles/Home.module.css";
// import { TextFields } from "@mui/icons-material";
// import { TextField } from "@mui/material";
import { Form_1 } from "@/components/Form_1";
//import { Buttons } from "@/components/Buttons";
// import { Boxes } from "@/components/Boxes";
// import { GridComponent } from "@/components/Grid";
//import GridCardConImagen from "@/components/GridCardConImagen";

export default function Home() {
  return (
    <>
      <Head>
        <title>Material UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} `}>
        {/* <Buttons/> */}
        {/* <GridCardConImagen/> */}
        {/* <Boxes/>
        <GridComponent/> */}        
        {/* <TextField id="filled-basic" label="Filled" variant="filled" color="secondary" />
        <TextField id="standard-basic" label="Standard" variant="standard"color="secondary" />
        <TextField id="outlined-basic" label="Outlined" variant="outlined" color="secondary" focused  /> */}
        <Form_1/>
      </main>
    </>
  );
}
